version: '3.7'
services:
  server:
    build: ./server
    ports:
    - 8080:8080
    networks:
     - htmlComparatorNetwork

  client:
    build: ./client
    ports:
      - 4200:4200
    networks:
      - htmlComparatorNetwork

networks:
  htmlComparatorNetwork:
     driver: bridge